api_shopp/api/urls.py
from django.urls import include, path
from django.conf.urls import url
from rest_framework import routers
from . import views
app_name = 'api'


router = routers.DefaultRouter()
router.register(r'product', views.ProductViewSet)
router.register(r'order', views.OrderViewSet)
router.register(r'Account', views.AccountViewSet)

urlpatterns = [
    path("shop/", views.index, name="ShopHome"),
    path("shop/about/", views.about, name="AboutUs"),
    path("shop/contact/", views.contact, name="ContactUs"),
    path("shop/search/", views.search, name="Search"),
    path("shop/checkout/", views.checkout, name="Checkout"),
    path("shop/products/<int:myid>", views.productView, name="ProductView"),
    path("shop/tracker/", views.tracker, name="TrackingStatus"),
    url(r'^$', views.user_login, name='user_login'),
    url(r'^sellerregd/$', views.register_seller, name="seller_register"),
    url(r'^sellerlogin/$', views.seller_login, name="seller_login"),
    url(r'^register/$', views.user_register, name='user_register'),
    path('api', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^thanks/$', views.thanks, name="thanks")
]

api_shopp/api_shopp/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,reverse
from django.conf.urls import url,include
from api import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^dappx/', include('api.urls')),
url(r'^search/', include('api.urls', namespace='search')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api_shopp/api/models.py
from django.db import models
from django.contrib.auth.models import User


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=100)

    def __str__(self):
        return self.company_name


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=10)


class Product(models.Model):

    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300)
    pub_date = models.DateField()
    seller_name = models.ForeignKey(Seller, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='shop/images', default="")
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.product_name


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json = models.CharField(max_length=5000)
    name = models.CharField(max_length=90)
    email = models.CharField(max_length=111)
    address = models.CharField(max_length=111)
    city = models.CharField(max_length=111)
    state = models.CharField(max_length=111)
    zip_code = models.CharField(max_length=111)
    phone = models.CharField(max_length=111, default="")


class OrderUpdate(models.Model):
    update_id  = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default="")
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:7] + "..."

api_shopp/api/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Seller,Customer


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')


class SellerRegisterForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = ('company_name',)


class CustomerRegisterForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('contact',)

api_shopp/api/views.py
import json
import itertools
from django.contrib import messages
from math import ceil
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from .forms import UserRegisterForm, SellerRegisterForm, CustomerRegisterForm
from rest_framework import viewsets
from .serializers import ProductSerializer, OrdersSerializer, LoginSerializer
from .models import Product, Orders, Seller, Customer,OrderUpdate
from django.http import HttpResponse
from django.core.mail import send_mail


# Rest API

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all().order_by('product_name')
    serializer_class = ProductSerializer


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Orders.objects.all().order_by('name')
    serializer_class = OrdersSerializer


class AccountViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all().order_by('username')
    serializer_class = LoginSerializer


# Views


# 1. Regsitrations


def register_seller(request):
    if request.method == 'POST':
        seller_creds = {
            'username': request.POST.get('username'),
            'first_name': request.POST.get('first_name'),
            'last_name': request.POST.get('last_name'),
            'email': request.POST.get('email'),
            'password': request.POST.get('password'),
        }
        user = User.objects.create_user(**seller_creds)
        seller = Seller(user=user, company_name=request.POST.get('company_name'))
        seller.save()
        return redirect('user_login')
    else:
        user_register_form = UserRegisterForm()
        seller_register_form = SellerRegisterForm()
    return render(request, 'registration/sellerregd.html',
    {
        'user_register_form': user_register_form,
        'seller_register_form': seller_register_form
    })


def user_register(request):
    if request.method == 'POST':
        customer_creds = {
            'first_name': request.POST.get('first_name'),
            'last_name': request.POST.get('last_name'),
            'email': request.POST.get('email'),
            'password': request.POST.get('password'),
            'username': request.POST.get('username')
        }
        user = User.objects.create_user(**customer_creds)
        customer = Customer(user=user, contact=request.POST.get('contact'))
        customer.save()
        return redirect('user_login')
    else:
        user_register_form = UserRegisterForm()
        Customer_register_form = CustomerRegisterForm()
    return render(request, 'registration/registration.html', {
        'user_register_form': user_register_form,
        'Customer_register_form': Customer_register_form
    })

# 2. Login Page


def seller_login(request):
    if request.method == 'POST':
        # Process the request if posted data are available
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Save session as cookie to login the user
            login(request, user)
            messages.info(request, f"You are now logged in as {username}")
            # Success, now let's login the user.
            return sellerindex(request)
        else:
            # Incorrect credentials, let's throw an error to the screen.

            return render(request, 'registration/sellerlogin.html',
                          {'error_message': 'Incorrect username and / or password.'})
    else:

        return render(request, 'registration/sellerlogin.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # Check username and password combination if correct
        user = authenticate(username=username, password=password)
        if user is not None:
            # Save session as cookie to login the user
            login(request, user)
            # Success, now let's login the user.
            return index(request)
        else:
            # Incorrect credentials, let's throw an error to the screen.
            return render(request, 'registration/login.html',
                          {'error_message': 'Incorrect username and / or password.'})
    else:
        # No post data available, let's just show the page to the user.
        return render(request, 'registration/login.html')
# HomePage


@login_required()
def index(request):
    customers = Customer.objects.all()
    cust_usernames = [customer.user.username for customer in customers]
    print(cust_usernames)
    for i in cust_usernames:
        if (i == request.user.username):
            allProds = []
            catprods = Product.objects.values('category', 'id')
            cats = {item['category'] for item in catprods}
            for cat in cats:
                prod = Product.objects.filter(category=cat)
                n = len(prod)
                nSlides = n // 4 + ceil((n / 4) - (n // 4))
                allProds.append([prod, range(1, nSlides), nSlides])

            params = {'allProds': allProds}
            return render(request, 'shopp/index.html', params)
        else:
            return HttpResponse("Account Not Found")


@login_required()
def sellerindex(request):
    sellers = Seller.objects.all()
    seller_usernames = [seller.user.username for seller in sellers]
    p = [seller.company_name for seller in sellers]
    print(seller_usernames)
    crecord = None
    allde = []
    Order = Orders.objects.all()

    desc = []
    names = []
    for i in seller_usernames:
        if i == request.user.username:
            sellername = i
            Order1 = Orders.objects.all().values('items_json', 'name')
            for i in Order1:
                s = ""
                t = " "
                name = ""
                qty = ""
                sum = 0
                for value in i:
                    a = i.get(value)
                    flag = 0
                    for key in a:
                        if flag == 1:
                            qty = key
                            flag = 0
                        if sum == 0 and key == "[":
                            flag = 1
                        if key == ',':
                            sum = sum + 1
                        if sum == 1 and key != '"' and key != ',' and key != "(":
                            t = t + key

                        if sum == 2 and key != "'" and key != "," and key != " " and key != '"':
                            s = s + key

                        if sum == 3 and key != "," and key != "}" and key != "]" and key != "0" and key != "1" and key != "2" and key != "3" and key != "4" and key != "5" and key != "6" and key != "7" and key != "8" and key != "9":
                            name = name + key
                if s == sellername:
                    desc.append(t)
                    names.append(name)
            print(names)
            print(desc)
            all = {}
            for i , j in itertools.product(names, desc):
                all.update({i: j})
            print(all)
            prod = Product.objects.all()
            allde.append([Order, prod, crecord, desc, sellername, all])
            params = {'allde' : allde}
            return render(request, 'shopp/sellerindex.html', params)
    return HttpResponse("No Account Found")


@login_required()
def thanks(request):
    if request.method == 'POST':
        status = request.POST.get('status', '')
        print(status)
        print(request.POST)
        send_mail("Message  ", status, "akshkhnay@gmail.com", ["akshaykhn7@gmail.com"], fail_silently=False)
        return HttpResponse("Thank You for sending. Your pay will be sent to you by admin to your account")

#Tracking Page

def tracker(request):
    if request.method == "POST":
        orderId = request.POST.get('orderId', '')
        email = request.POST.get('email', '')
        try:
            order = Orders.objects.filter(order_id=orderId, email=email)
            if len(order) > 0:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                for item in update:
                    updates.append({'text': item.update_desc, 'time': item.timestamp})
                    response = json.dumps([updates, order[0].items_json], default=str)
                return HttpResponse(response)
            else:
                return HttpResponse('{}')
        except Exception as e:
            return HttpResponse('{}')

    return render(request, 'shopp/tracker.html')

#About Page


def about(request):
    return render(request, 'shopp/about.html')

#Contact Page


def contact(request):
    return render(request, 'shopp/contact.html')

#Product View


def productView(request, myid):
    product = Product.objects.filter(id=myid)
    return render(request, 'shopp/prodView.html', {'product': product[0]})


# Checkout
def checkout(request):
    if request.method == "POST":
        items_json = request.POST.get('itemsJson', '')
        a = json.loads(items_json)
        a1=0
        a2=""
        for key,value in a.items():
            a1=value[0]
            a2= value[1]
        a21 = Product.objects.get(product_name=a2)
        id= a21.id
        prod = Product.objects.get(id=id)

        names = [prod.product_name for prod in Product.objects.all()]
        for i in names:
            if i == a2:
                prod.quantity = prod.quantity - a1
                if prod.quantity == 0:
                    prod.save()
                    messages.info(request, 'Order has gone out of stock')
                    return render(request, 'shopp/checkout.html')



        name = request.POST.get('name', '')

api_shopp/api/templates/shopp/about.html
{% extends 'shopp/basic.html' %}

{% block title %} Title of About {% endblock %}
{% block body %}

<h1> This Is a Sample Project made By AKSHAY Khan</h1>

{% endblock %}

api_shopp/api/templates/shopp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"></head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">{# Django Home Link / Admin Link / Register Link#}


          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

api_shopp/api/templates/shopp/basic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
     <style>
       {% block css %} {% endblock %}
  </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/shop">Shopp.COM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/shop">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/shop/about">About Us</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/shop/tracker">Tracker</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="/shop/contact">Contact Us</a>
      </li>

    </ul>
    <form method='get' action='/shop/search/' class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true" data-content="Vivamus
sagittis lacus vel augue laoreet rutrum faucibus.">


  Cart(<span id="cart">0</span>)
</button>
  </div>
</nav>
  {% block body %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block js %} {% endblock %}
  </body>
</html

api_shopp/api/templates/shopp/basic2.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title%} {% endblock %}</title>
     <style>
       {% block css %} {% endblock %}
  </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/shop">Shopp.COM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/shop">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/shop/about">About Us</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/shop/tracker">Tracker</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="/shop/contact">Contact Us</a>
      </li>

    </ul>
  </div>
</nav>
  {% block body %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {% block js %} {% endblock %}
  </body>
</html

api_shopp/api/templates/shopp/checkout.html
{% extends 'shopp/basic.html' %}
{% block title%} Checkout - Shopp.com{% endblock %}
{% block body %}
<div class="container">
    <div class="col my-4">
        <h2>Step 1 - Shopp.COM Express Checkout - Review Your Cart Items</h2>
        <div class="my-4">
            <ul class="list-group" id="items">
            </ul>

            <nav aria-label="breadcrumb">
  <ol class="breadcrumb mt-3">
    <li class="breadcrumb-item active" aria-current="page">Your Cart Total Is <b>Rs. <span id="totalPrice"></span></b>. Enter your details below & place your order. Thanks for using My Awesome Cart!</li>
  </ol>
</nav>




        </div>
    </div>
    <div class="col my-4">
        <h2>Step 2 - Enter Address & Other Details:</h2>
        <form method="post" action="/shop/checkout/">{% csrf_token %}
            <input type="hidden" name="itemsJson" id="itemsJson">
            <input type="hidden" name="amount" id="amount">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputname">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="address1" name="address1" placeholder="1234 Main St">
            </div>
            <div class="form-group">
                <label for="inputAddress2">Address line 2</label>
                <input type="text" class="form-control" id="address2" name="address2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" name="state"  placeholder="Enter State">
                </div>
                <div class="form-group col-md-2">
                    <label for="inputZip">Zip</label>
                    <input type="text" class="form-control" id="zip_code" name="zip_code">
                </div>
            </div>
            <div class="form-group">
                <label for="inputZip">Phone Number</label>
                <input type="tel" class="form-control" id="phone" name="phone">
            </div>
            <button type="submit" class="btn btn-primary">Place Order</button>
        </form>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));

}
console.log(cart);
var sum = 0;
var totalPrice = 0;

if ($.isEmptyObject(cart)) {
    //if object is empty
    mystr = `<p>Your cart is empty, please add some items to your cart before checking out!</p>`
    $('#items').append(mystr);
} else {
    for (item in cart) {
        let name = cart[item][1];
        let qty = cart[item][0];
        let itemPrice = cart[item][2];
        sum = sum + qty;
        console.log(itemPrice);
        totalPrice = totalPrice + qty* itemPrice;
        mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                    <span class="badge badge-primary badge-pill">${qty}</span>
                </li>`
        $('#items').append(mystr);
    }

}

document.getElementById('cart').innerHTML = sum;
document.getElementById('totalPrice').innerHTML = totalPrice;
$('#itemsJson').val(JSON.stringify(cart));
{% if thank %}
alert('Thanks for ordering with us. Your order is is {{id}}. Use it to track your order using our order tracker');
localStorage.clear();
document.location = "/shop";
{% endif %}
$('#amount').val($('#totalPrice').html())
</script>
{% endblock %}

api_shopp/api/templates/shopp/contact.html
{% extends 'shopp/basic.html' %}

{% block body %}
<div class="container">
  <h1>Contact Us !!!!</h1>
<form action="/shop/contact/" method="POST" >{% csrf_token %}
  <div class="form-group">
    <label for="exampleFormControlTextarea2">Name</label>
    <input class="form-control" id="exampleFormControlTextarea2" name= "name"
           placeholder="Enter Your Name"> </input>
  </div>
     <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1"
           name="email" placeholder="Enter Your Email-Id">
  </div>
  <div class="form-group">
    <label for="mobilenumber">Mobile Number</label>
    <input type="tel" class="form-control" id="mobilenumber" name="mobilenumber" placeholder="Enter
 Your Mobile Number">
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Message</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" name="message"
              placeholder="Enter Your Message" rows="3"
               style="margin-top: 0px; margin-bottom: 0px; height: 200px;"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>


{% endblock %}

api_shopp/api/templates/shopp/index1.html
{% extends "shopp/base.html" %}
{% block body_block %}<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Shopp.COM!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>{% endblock %}

api_shopp/api/templates/shopp/sellerindex.html
{% extends 'shopp/basic2.html' %}
{% block title%} Shopp.Com - Best Ecommerce Website{% endblock %}
{% block css %}
.col-md-3
{
display: inline-block;
margin-left:-4px;
}
.carousel-indicators .active {
background-color: blue;
}
.col-md-3 img{
width: 170px;
height: 200px;
}
body .carousel-indicator li{
background-color: blue;
}
body .carousel-indicators{
bottom: -40px;
}
.carousel-indicators li {


    background-color: #7270fc;
}
body .carousel-control-prev-icon,
body .carousel-control-next-icon{
background-color: blue;
}
.carousel-control-prev,
.carousel-control-next{
top: auto;
bottom: auto;
padding-top: 222px;
}
body .no-padding{
padding-left: 0,
padding-right: 0;
}
{% endblock %}
{% block body %}
{% load static %}

<table class="table" xmlns="http://www.w3.org/1999/html">
  <thead>
    <tr class="bg-success"></tr>
      <th scope="col">Name</th>
      <th scope ="col">email</th>
      <th scope ="col">City</th>
     <th scope ="col">state</th>
      <th scope ="col">zip_code</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
      <th scope="col">Order</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    {% for product,prod,crecord,desc,sellername,all in allde %}
     <div class="alert alert-danger" role="alert">

         Welcome {{sellername}} !!!!
         You have a Order of
         <br>
         <br>
         Order   :  Name
         <br>
         {% for i,j in all.items %}
         * {{i}} : {{j}}
         <br>
         {% endfor %}
         <br>
         <br>
         Note :  For Adding your Products into the website mail the info with of the product with Proper Details.
    </div>
     {% for j in product %}

      <td class="bg-warning">{{j.name}}</td>
      <td class="bg-success">{{j.email}}</td>
      <td class="bg-success">{{j.city}}</td>
        <td class="bg-warning">{{j.state}}</td>
        <td class="bg-warning">{{j.zip_code}}</td>
      <td class="bg-info">{{j.address}}</td>
      <td class="bg-info">{{j.phone}}</td>
      <td class="bg-danger">{{j.items_json}}</td>
      <form action="{% url 'api:thanks' %}" method="post">{% csrf_token %}
      <td class="bg-success">
          <div class="form-group">
            <input type="text" class="form-control" id="status" size="400" name="status" title="status" placeholder="Enter Your Status with the Company Name">
              <input type="submit"  class="btn btn-primary">
           </div>
      </td>
      </form>
    </tr>
      {% endfor %}
    {% endfor %}
  </tbody>
</table>
    </form>
{% endblock %}